/*$file${../src::ClockAlarm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: ClockAlarm.qm
* File:  ${../src::ClockAlarm.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../src::ClockAlarm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"
#include "lcd.h"
#include "ClockAlarm.h"
/*$declare${HSMs::Clock_Alarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${HSMs::Clock_Alarm} .....................................................*/
typedef struct 
{
/* protected: */
    QHsm super;

/* private: */
    QTimeEvt timeEvt;

/* private state histories */
    QStateHandler hist_Clock;
} Clock_Alarm;

/* protected: */
static QState Clock_Alarm_initial(Clock_Alarm * const me, void const * const par);
static QState Clock_Alarm_Clock(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Ticking(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Clock_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Alarm_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Alarm_Notify(Clock_Alarm * const me, QEvt const * const e);
/*$enddecl${HSMs::Clock_Alarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
